### ISSUE TITLE
Job Types on dashboard shows inactive jobs

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#120]
job_types which have is_active=='False' should never be shown in dropdowns, lists, or gallery views,.  

Job Types gallery should have toggle to show active/deprecated
Recipe Types Gallery should have an option to toggle active/deprecated
Metrics page will need to be special... By default, should not show deprecated jobs in the picker, but... since metrics COULD be gathered for past historical reports, there need to be options to show deprecated jobs or recipes.  At the same time, we should treat versions of same job type as being related.

**Comment by ericsvendsen-mil** [comment]
Ok, there's a lot going on in this issue.

First, just to clarify some terminology, there's technically no such thing as an "inactive" job type. The two states are referred to as "active" and "deprecated".

- Removing deprecated job types from all dropdowns, lists, and gallery views was done in issues #46 and #52.
- The job types list on the dashboard is derived from `/job-types/status/`, which has no server-side filtering for active/deprecated job types. Additionally, the payload returned from that call does not contain information on whether a job type is active or deprecated. As a result, when I first addressed this question in issue #55, my filtering removed all job types from the dashboard. [You can see here where I reverted this change.](https://github.com/ngageoint/scale-ui/commit/ce491601dda2caf45d7bc122d0632b2ff7854fe4#diff-d20ce8a9e8eed42469ec231c75793154) Therefore any changes you want to see in this regard will need to also be add as an issue on the main Scale repo to update the job types status API call.
- Job Types and Recipe Types views already have a toggle control for active/deprecated. This was done in commit 819725a.
- Anything related to changing how metrics should be shown or additional features to the metrics view should be entered as a separate issue.

I'll leave this issue open for now, since I'm sure you saw *something* in the UI that caused you to open this. It might be best to discuss all of this in person before deciding where to go from here.

**Comment by cshamis** [comment]
Agreed

**Comment by ericsvendsen-mil** [comment]
Filtering deprecated job types out of the dashboard list depends on ngageoint/scale#1696
