### ISSUE TITLE
Job Type History only populating Last 30 days column

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#284]
Related to #283...

When the Job Type History is populating, only the furthest column on the right (last 30 days) has information in it.  

In looking at Scale Ingest and one CB... Job Types I know there have been system failures for in the last 24 hours. 

Jonathan Meyer did a check and said the back-end is sending the messages. 

Nothing is populating in the first 2 columns (last 24 hours, last 48 hours).

**Comment by emimaesmith** [comment]
The data coming back from the /api/v6/plot-data request contains values using the new `datetime` instead of `date`. I suspect this isn't being handled properly by the UI as the only place (I am aware of) we were looking to update when the metrics API was updated was the dashboard.

Sample JSON coming back from the API for the call to retrieve job type history:
```
{
   "count": 4,
    "next": null,
    "previous": null,
    "results": [{
        "column": {
            "name": "error_system_count",
           "title": "System error count",
           "description": "number of failed jobs due to a system error.",
           "units": "count",
           "group": "errors",
           "aggregate": "sum"
        },
        "min_x": "2019-07-31T00:00:00Z",
        "max_x": "2019-08-20T00:00:00Z",
        "min_y": 11,
        "max_y": 345,
        "values":[{"datetime": "2019-07-31T00:00:00Z", "value": 1, "id":6},{"datetime": "2019-07-31T00:00:00Z", "value": 0, "id": 10},
```

**Comment by emimaesmith** [comment]
Can confirm when the metrics API is updated to bin the data by hour, the job type history table will need to be updated. Closing as a non-issue.
