### ISSUE TITLE
Ux: Nice to have- Improvements for Selection View

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#296]
In the different views that allow a drop down and selected options, it would be nice if the column headers included the selected without having to click on anything.  

It would be nice to be able to save the selected view between usages.

**Comment by mheppner** [comment]
Closing because I don't think this is feasible.

> it would be nice if the column headers included the selected without having to click on anything.
If this is directed towards the multiselect components, I don't think it would be wise to show the labels of everything selected directly in the header. You could easily select 50, 100+ items in a multiselect. Currently it just displays "<num> selected items." An extra click is the tradeoff for having a 1000px long column header displaying all of the labels.

> It would be nice to be able to save the selected view between usages.
The datatable filters are persisted to local storage and should repopulate themselves when you return to the view you're on.
