### ISSUE TITLE
Filename search for ingests

### ISSUE THREAD

**Issue by Rachel-ais** [ngageoint/scale-ui#355]
add a search box to find a specific filename in ingest records

**Comment by cshamis** [comment]
Thx Rachel!

**Comment by emimaesmith** [comment]
The /ingest API endpoint supports a file_name query parameter. The filtering, however, requires an exact match on file name instead of doing a 'like' comparison. The UI portion to allow filtering on filename has been completed. To fully support this functionality we'll need to update the API to allow for like name filtering instead of exact. 

Created https://github.com/ngageoint/scale/issues/1811 to address the API update.
