### ISSUE TITLE
Live range giving other values

### ISSUE THREAD

**Issue by Rachel-ais** [ngageoint/scale-ui#433]
![Screen Shot 2020-02-07 at 12 58 44 PM](https://user-images.githubusercontent.com/48250701/74053356-a5e88080-49a9-11ea-846a-c04063cd0fa8.png)

When selecting a recipe type in the recipe table it will ignore the live range until it refreshes

**Comment by mheppner** [comment]
From @saradarrah:
> Choose “last week” . Note the total number of jobs that are in the parentheses. Also sort by time created and note the most recent job. Then go to the date range and choose one week. Note the total jobs...the number was different for me on base. Then do the same sort...for me “six hours ago” was the most recent job that showed up in the date range even though the “last week” had jobs that ran a few seconds ago.

**Comment by mheppner** [comment]
This is in fact a bug. Since the timer in the live range component was driving the API call in the parent datatable components, the parent components were not saving those values. When additional filters were applied (sorting, selected recipe types, etc), a query was sent with just the filters and no start/stop times. The next time the live range updated, then the correct query was sent.

However, this is getting closed in favor of #445 to discuss bigger changes related to live range mode.
