### ISSUE TITLE
New Recipe Status Component for Dashboard

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#481]
The Recipe Status Component will provide a way for users to follow their favorite recipes.  The status view will allow users to see the status of a recipe, the status of each pre-determined phase of the recipe, the current/total processing time and include a link to products created.  
Wireframe (note this is an example and should not be taken as end design): 
![image](https://user-images.githubusercontent.com/45433277/81304207-c24c9580-904a-11ea-81ee-925bf3aec904.png)
Details:
1. Initially the component will be blank.  A user will need to add their favorite recipes (functionality shown in the prototype in the upper right corner with the + sign)
2. Once a user adds a recipe, they will see a Overall Status, the Name of the Recipe, Recipe phases, the current/total processing time and a link to the products. 

- Overall Status options: Complete/In Progress

- Recipe phases: Data Ingest/Data Parse (if applicable)/Jobs (one dot to represent all jobs with the ability to expand to see details for each job)/Data Created/Data published (if applicable)

- Recipe phase status options: Not started, In Progress, Complete, Failed
not started - all X are pending or queued
in progress - any X are running
complete - all X are complete
failed - any X have failed
Where X is the phase option (exception is data ingest)

- Processing Time: If the recipe is In Progress the time will show how much time has currently passed from beginning to present. If the Recipe Failed or is Complete the Processing Time should show the total time from beginning to complete/failed step. 

- Products will be a link to all products created by that recipe and should be available once the first data product is created from the recipe. This will be a new modal that opens consolidating all the products available from each job. 

- Users can click on Data Parse, Jobs, Data Created and Data published to have a detailed view listing all applicable recipe components and their individual status of Not started/In Progress, Complete or Failed. 

The dashboard will be limited to initially show 10 recipes with a scroll bar if there are more than 10.  Recipes should remain on the board as long as they are In Progress. Recipes should remain on the progress board for 7 days after they have passed- but allow users to delete that recipe from the view if desired.  Recipes should remain on the progress board for 7 days after they have failed- but allow users to restart or delete the recipe instance from the view if desired.

**Comment by mheppner** [comment]
Notes from today's meeting:
- job type favorites will be separate from recipe type favorites
  - favorites are only stored in localstorage in the browser
  - job types are only favorited on the dashboard
  - need a new interface for favoriting recipe types
- overall status column
  - no direct definition of what makes a recipe complete/failed/etc
  - due to some branching, conditionals, or "optional jobs," (eg a job that may log something to ES fails, but rest of recipe is success), may not want to consider an entire recipe as "failed"
  - -> limit to "in progress" and "complete" (directly from `is_complete` field)
- ingest phase/bubble - a special ingest job that makes Scale aware of files
  - no direct way of tracking it, since the recipe instance doesn't exist yet
  - only association is the scan or strike ID
  - recipe instance only exists/starts once Scale has completed the ingest job
  - -> show first bubble as green (always/static) since the recipe instance wouldn't have shown up without this running
- overall bubble status - for remaining bubbles, status should be as follows:
  - not started - all jobs are pending or queued
  - in progress - any jobs are running
  - complete - all jobs are complete
  - failed - any jobs have failed
- parse bubble - no direct way of figuring out parse jobs
  - parse job cracks open files and discovers more metadata
  - not a special job, just a normal job in the recipe, but typically named with "parse"
  - could be more than one in a recipe
  - additional ideas
    - parse jobs may create specific .json manifest files - doesn't help because you'd have to inspect file outputs after it runs
    - events may have something specific for parse?
    - `source_*` fields on the job instance?
  - -> filter jobs of recipe by job type's title and description field
- published bubble - additional special case bubble
  - look at job types in recipe instance to see if any of them have an `is_published` flag
  - create new bubble just for this and add any jobs with `is_published` flag to it
- jobs bubble - all remaining jobs
  - everything else except `is_published` and "parse" jobs
  - -> status bubble for all remaining filtered jobs
- data created bubble
  - mark as in progress if any job in recipe is complete
  - on job type, there is an `outputs` property where the output files/json is defined
  - if job has any `outputs` and it is in complete status, then consider as having written output
  - -> filter jobs by ones with `outputs` defined and generate overall status
- total processing time
  - should this be actual processing time (summation of each job's duration) or elapsed time (recipe start to end - would include Scale overhead and IO)
  - will be using recipe's `created` and `completed` datetime fields
  - if any job fails in the recipe, the completed time is left blank
- products link
  - both job types and recipe types can be configured to have an output workspace
  - this means there is no place to link to to view everything output from a recipe
  - don't have any existing interface to view this aggregate data anyways (rows on the ingest records page point to the job)
  - -> leave off for now, or provide a modal that shows all files, filtered by the recipe id
- misc
  - may want to create new API endpoint to handle these queries
  - no auto refreshing, provide a manual button instead

I think these are the steps needed with the API:
1. get `/recipe-types` to allow user to pick favorites
2. get `/recipes?recipe_types=x` filtered with the favorites
3. for each recipe instance, filter out parse and `is_published` jobs and build corresponding bubbles
4. use `/files?recipe_id=x` to show modal of files related to the recipe
