### ISSUE TITLE
Dashboard Pie Chart Constantly Refreshes When Scale Tab Regains Focus (chrome)

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale-ui#484]
The Running Jobs Pie Chart will refresh upwards of 50+ times when returning the Scale tab from any other browser tab or application. All other charts only refresh once or twice.

Steps to reproduce:
1. Open Scale to the dashboard. Note that the pie chart refreshes twice.
2. Switch to a new tab in the browser or other application altogether.
3. Switch back to the Scale tab. Note that the pie chart refreshes 50+ times before finally stabilizing.

Seen mainly in Chrome 81.0.4044.138
Doesn't appear to happen in Firefox 75.0 (64-bit)
Doesn't appear to happen in Safari 13.1 (15609.1.20.111.8)
Have not tested in Edge

**Comment by mheppner** [comment]
I can't reproduce this in Chrome 83.0.4103.61, but I do see all the charts refresh twice - a total of 8 requests in Chrome and 13 in FF 76.0.1. Not sure why there's a difference, but maybe it's related to the excessive refreshes you're seeing.

**Comment by mheppner** [comment]
Actually, I think your issue is related to the number of favorites are selected? The numbers in my previous comment were with 0 favorites. Now I'm seeing 25 req for 2 favorites, 47 req for 4 favorites, 77 req for 6 favorites.

I only see the pie chart repaint/draw like twice though. May just because I'm using the local dev server so the requests come back quickly.
