### ISSUE TITLE
Enforce one connection per input slot on jobs in recipe builder.   

### ISSUE THREAD

**Issue by Nikkala-AIS** [ngageoint/scale-ui#495]
For job types with two inputs, it is possible to assign two connections to one input and then it is impossible to assign a connection to the second input.  

To duplicate (using mock UI):
Go to recipe builder page
Click on "+" to create a new recipe
Add job "constrained energy minimization" (a job that has two+ slots for inputs)
Add one or more input files
Click on the job in the recipe diagram and assign two files to the first input slot
You will be unable to add a file to the second input slot

**Comment by emimaesmith** [comment]
Clarification of this issue:
The UI does not remove the '+' button when an input connection has been selected for a given input when there are multiple inputs defined for a job type. 

Expected behavior:
When an input connection has been selected, the UI should remove the '+' button from that specific input. Changes to that input connection need to be made by first removing the previous connection, and re-selecting the input.
