### ISSUE TITLE
System Status

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale-ui#50]
Relies on ngageoint/scale#1532

**Comment by cshamis** [comment]
Under the "Scale Health" indicator button I think we need PASS/FAIL checks on the following:

LOGS (fluentd)
SCALE (scheduler)
SECRETS (Vault)
SILO (SILO should report a fail if SILO cannot talk to it's configured container repos too)
DATABASE
SYSTEM (Clock, Strikes, other??) System jobs must *never* fail.  They may be running or paused, but not queued, pending or failed.
MSGBUS
IDAM (GEOAxIS ... or whatever only if configured)
NODES (if > 1/3 become unhealthy then go red?) 

In order to prevent alarm fatigue these events must be serious enough to warrant action.  I'm on the fence about the nodes, but I kinda think we should do something.

Also, if logged in as an ADMIN do we need a power button to start/stop the scheduler?  Then the "health" button doesn't pull double duty as a place to pause unpause?

**Comment by cshamis** [comment]
https://unicodepowersymbol.com/

**Comment by ericsvendsen-mil** [comment]
This will be part of the system status as described in #124

**Comment by ericsvendsen-mil** [comment]
Renamed this issue to better reflect what it needs to accomplish. Here is a summary of what is left:

Modify scheduler status dropdown to handle all system status updates. This will be a list of status items in the comment above (as well as scheduler) that will have icons which immediately indicate whether something is in trouble. At the bottom of the dropdown there will be a link to a view with more detail for each status item. There is currently a placeholder component for the status detail available at `/system/status`.
